### ISSUE TITLE
Automated email format - images not well sized - Canonical branding too evident

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical-web-and-design/kubeflow-news.com#62]
Hi all, 

Looking at the first email I received from Kubeflow-news, the format seems a bit out of proportion - very small text, huge images. 

Also, this is branded in the end as Canonical | Ubuntu and this should be an agnostic mailing. So I believe we should remove that as well. We can add Kubeflow-news twitter: https://twitter.com/kubeflownews

View below: 

![KF-news](https://user-images.githubusercontent.com/27001378/89925312-227b4680-dbfb-11ea-8235-a1d502c91811.png)

---
*Reported from: https://kubeflow-news.com/

**Comment by RFMVasconcelos** [comment]
Hi @pmahnke!

I don't know if you get an automated notice on this, so I am just tagging you to let you know of this issue. Could you please assign it to the person in charge?

Many thanks!
Rui

**Comment by pmahnke** [comment]
@RFMVasconcelos 

1. images

perkuto is pretty simple, we just get a blob of html from workpress.  I did try to a) center and b) max-width 250px the images

![image](https://user-images.githubusercontent.com/441217/90001154-f73f3880-dc88-11ea-97d9-1c36358c6c35.png)

does that look better?

2. Canonicalness

I assume you mean the footer?  If Thibaut is ok with it, we can update that... what are you thinking?

**Comment by RFMVasconcelos** [comment]
Hi @pmahnke, 

Thank you for touching this so quickly! 

1. The images and font look great like that!
2. I would have in **very small font**:

```
This content is produced and curated by Canonical Ltd. as a contribution to the Kubeflow community. Find out more in www.ubuntu.com/kubeflow.


© Canonical Ltd. Ubuntu and Canonical are registered trademarks of Canonical Ltd.
```

What do you think?

**Comment by pmahnke** [comment]
@RFMVasconcelos well, _all_ the newsletters have that footer, so it seems odd to change it for this one.  I don't think we are fooling anyone by not being Canonical.  And, it would look better with more text in the post, there is almost none, so it stands out more as a result.
