### ISSUE TITLE
No way to contact us

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical-web-and-design/kubeflow-news.com#73]
Could we have an email at least for the case of people wanting to publish to Kubeflow-news?

**Comment by RFMVasconcelos** [comment]
cc @SirSamTumless @pmahnke

**Comment by pmahnke** [comment]
@RFMVasconcelos what is best? Do you have a generic email?  What would the CTA be?  Or could they be leads as well? Then we need a marketo form.

**Comment by RFMVasconcelos** [comment]
Hey @pmahnke! I will ask IS for a `contact@kubeflow-news.com` email, I guess we could simply add a link to it.

**Comment by anthonydillon** [comment]
@RFMVasconcelos did you manage to get the email set up?

**Comment by pmahnke** [comment]
@anthonydillon yes he has, sorry I thought he replied here

**Comment by pmahnke** [comment]
Completed a while ago.
